#ifndef TWCLOCK_APP_CONFIG_H
#define TWCLOCK_APP_CONFIG_H

#define TWCLOCK_WIDTH 300
#define TWCLOCK_HEIGHT 96
#define TWCLOCK_MARGIN_TOP 24
#define TWCLOCK_MARGIN_RIGHT 24

#define TWCLOCK_BUFFER_COUNT 2

#endif /* TWCLOCK_APP_CONFIG_H */
