name = "txpc-test-server"
description = "TXPC bootstrap test server"
exec = "/bin/txpc_echo_service"
args = []
enabled = false
runlevel = "default"
restart = "never"
type = "foreground"
stdout = "log"
stderr = "log"

[txpc]
name = "dev.twilight.test"
on_demand = true

[txpc.policy]
allow_uids = [0]
require_cap = ["gui"]
